// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA92hFwdqqgSqq4tnSwiSOn5KtD4-fzT9o',
    appId: '1:19643608581:web:660128e87f92259b69f66c',
    messagingSenderId: '19643608581',
    projectId: 'sabia-0000',
    authDomain: 'sabia-0000.firebaseapp.com',
    storageBucket: 'sabia-0000.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6wYZg17bGy-KlzVtxP7lsdasEEY6C3aU',
    appId: '1:19643608581:android:6c85f52e2ff86c5c69f66c',
    messagingSenderId: '19643608581',
    projectId: 'sabia-0000',
    storageBucket: 'sabia-0000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwuSD1RN7fmZfGygdsOm-lXrZ2cVknQOk',
    appId: '1:19643608581:ios:1c22c78399a5635369f66c',
    messagingSenderId: '19643608581',
    projectId: 'sabia-0000',
    storageBucket: 'sabia-0000.firebasestorage.app',
    iosBundleId: 'com.example.sabia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwuSD1RN7fmZfGygdsOm-lXrZ2cVknQOk',
    appId: '1:19643608581:ios:1c22c78399a5635369f66c',
    messagingSenderId: '19643608581',
    projectId: 'sabia-0000',
    storageBucket: 'sabia-0000.firebasestorage.app',
    iosBundleId: 'com.example.sabia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA92hFwdqqgSqq4tnSwiSOn5KtD4-fzT9o',
    appId: '1:19643608581:web:4a4d2344a84254df69f66c',
    messagingSenderId: '19643608581',
    projectId: 'sabia-0000',
    authDomain: 'sabia-0000.firebaseapp.com',
    storageBucket: 'sabia-0000.firebasestorage.app',
  );
}
